/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_COLON_COLON = 3,
  anon_sym_verify = 4,
  anon_sym_import = 5,
  anon_sym_LBRACE = 6,
  anon_sym_COMMA = 7,
  anon_sym_RBRACE = 8,
  anon_sym_COLON = 9,
  anon_sym_DASH_DASH = 10,
  anon_sym_SLASH_SLASH = 11,
  aux_sym_comment_token1 = 12,
  aux_sym_raw_value_token1 = 13,
  sym_string = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  sym_version = 17,
  sym_number = 18,
  sym_path_value = 19,
  sym_path = 20,
  sym_identifier = 21,
  sym_source_file = 22,
  sym__definition = 23,
  sym_section = 24,
  sym_scope_entry = 25,
  sym_scope_return = 26,
  sym_verify_statement = 27,
  sym_import_statement = 28,
  sym_assignment = 29,
  sym_list_item = 30,
  sym_comment = 31,
  sym__value = 32,
  sym_raw_value = 33,
  sym_boolean = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_import_statement_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_verify] = "verify",
  [anon_sym_import] = "import",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_raw_value_token1] = "raw_value_token1",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_version] = "version",
  [sym_number] = "number",
  [sym_path_value] = "path_value",
  [sym_path] = "path",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_section] = "section",
  [sym_scope_entry] = "scope_entry",
  [sym_scope_return] = "scope_return",
  [sym_verify_statement] = "verify_statement",
  [sym_import_statement] = "import_statement",
  [sym_assignment] = "assignment",
  [sym_list_item] = "list_item",
  [sym_comment] = "comment",
  [sym__value] = "_value",
  [sym_raw_value] = "raw_value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_statement_repeat1] = "import_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_verify] = anon_sym_verify,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_raw_value_token1] = aux_sym_raw_value_token1,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_version] = sym_version,
  [sym_number] = sym_number,
  [sym_path_value] = sym_path_value,
  [sym_path] = sym_path,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_section] = sym_section,
  [sym_scope_entry] = sym_scope_entry,
  [sym_scope_return] = sym_scope_return,
  [sym_verify_statement] = sym_verify_statement,
  [sym_import_statement] = sym_import_statement,
  [sym_assignment] = sym_assignment,
  [sym_list_item] = sym_list_item,
  [sym_comment] = sym_comment,
  [sym__value] = sym__value,
  [sym_raw_value] = sym_raw_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_statement_repeat1] = aux_sym_import_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_verify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_path_value] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_return] = {
    .visible = true,
    .named = true,
  },
  [sym_verify_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 1,
        ',', 27,
        '-', 3,
        '/', 5,
        ':', 29,
        '[', 15,
        ']', 17,
        'f', 75,
        'i', 82,
        't', 85,
        'v', 78,
        '{', 26,
        '}', 28,
        0x17f, 105,
        0x212a, 105,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(45);
      if (lookahead == 't') ADVANCE(55);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2);
      if (lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '@') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(18);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 10:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 11:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 40,
        '-', 41,
        '/', 43,
        ':', 44,
        '[', 16,
        'f', 45,
        'i', 52,
        't', 55,
        'v', 48,
      );
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(12);
      if (lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(98);
      if (lookahead == 'v') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(18);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      ADVANCE_MAP(
        '"', 40,
        '-', 41,
        '/', 43,
        ':', 44,
        '[', 16,
        'f', 45,
        'i', 52,
        't', 55,
        'v', 48,
        0x17f, 63,
        0x212a, 63,
        '\t', 38,
        0x0b, 38,
        '\f', 38,
        ' ', 38,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(67);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      ADVANCE_MAP(
        '"', 40,
        '/', 43,
        'f', 45,
        't', 55,
        0x17f, 63,
        0x212a, 63,
        '\t', 39,
        0x0b, 39,
        '\f', 39,
        ' ', 39,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(67);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == '"') ADVANCE(67);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(1);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == '.') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == '/') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'e') ADVANCE(70);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'f') ADVANCE(61);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'i') ADVANCE(49);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'l') ADVANCE(58);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'm') ADVANCE(54);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'o') ADVANCE(57);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'p') ADVANCE(53);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'r') ADVANCE(60);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'r') ADVANCE(59);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 's') ADVANCE(47);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'u') ADVANCE(46);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'y') ADVANCE(22);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_raw_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(63);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(67);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_version);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'a') ADVANCE(81);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'e') ADVANCE(86);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(91);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(79);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(88);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'm') ADVANCE(84);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'p') ADVANCE(83);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(80);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(89);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 't') ADVANCE(23);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'u') ADVANCE(76);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'y') ADVANCE(20);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(93);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_path_value);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'e') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'm') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(102);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'p') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == 'y') ADVANCE(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(105);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 13},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 35},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_verify] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_path_value] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym__definition] = STATE(6),
    [sym_section] = STATE(8),
    [sym_scope_entry] = STATE(8),
    [sym_scope_return] = STATE(8),
    [sym_verify_statement] = STATE(8),
    [sym_import_statement] = STATE(8),
    [sym_assignment] = STATE(8),
    [sym_list_item] = STATE(8),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_COLON_COLON] = ACTIONS(9),
    [anon_sym_verify] = ACTIONS(11),
    [anon_sym_import] = ACTIONS(13),
    [anon_sym_DASH_DASH] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_comment] = STATE(2),
    [sym__value] = STATE(15),
    [sym_raw_value] = STATE(10),
    [sym_boolean] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_COLON_COLON] = ACTIONS(21),
    [anon_sym_verify] = ACTIONS(21),
    [anon_sym_import] = ACTIONS(21),
    [anon_sym_DASH_DASH] = ACTIONS(21),
    [anon_sym_SLASH_SLASH] = ACTIONS(23),
    [aux_sym_raw_value_token1] = ACTIONS(25),
    [sym_string] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_version] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [sym_path_value] = ACTIONS(27),
    [sym_identifier] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      anon_sym_verify,
    ACTIONS(13), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_DASH_DASH,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(6), 1,
      sym__definition,
    STATE(8), 7,
      sym_section,
      sym_scope_entry,
      sym_scope_return,
      sym_verify_statement,
      sym_import_statement,
      sym_assignment,
      sym_list_item,
  [43] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(38), 1,
      anon_sym_COLON_COLON,
    ACTIONS(41), 1,
      anon_sym_verify,
    ACTIONS(44), 1,
      anon_sym_import,
    ACTIONS(47), 1,
      anon_sym_DASH_DASH,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(6), 1,
      sym__definition,
    STATE(4), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(8), 7,
      sym_section,
      sym_scope_entry,
      sym_scope_return,
      sym_verify_statement,
      sym_import_statement,
      sym_assignment,
      sym_list_item,
  [84] = 7,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(25), 1,
      aux_sym_raw_value_token1,
    STATE(5), 1,
      sym_comment,
    STATE(12), 1,
      sym__value,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_raw_value,
      sym_boolean,
    ACTIONS(27), 5,
      sym_string,
      sym_version,
      sym_number,
      sym_path_value,
      sym_identifier,
  [112] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(6), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(53), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [130] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(7), 1,
      sym_comment,
    ACTIONS(59), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [148] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(8), 1,
      sym_comment,
    ACTIONS(63), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [166] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(9), 1,
      sym_comment,
    ACTIONS(67), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [184] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(10), 1,
      sym_comment,
    ACTIONS(71), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [202] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(11), 1,
      sym_comment,
    ACTIONS(75), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [220] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(79), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [238] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(83), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [256] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [274] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(91), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(89), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [292] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(93), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [310] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(99), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(97), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [328] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(103), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [346] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(107), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [364] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      sym_comment,
    STATE(21), 1,
      aux_sym_import_statement_repeat1,
  [380] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_import_statement_repeat1,
  [396] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(22), 2,
      sym_comment,
      aux_sym_import_statement_repeat1,
  [410] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(23), 1,
      sym_comment,
  [423] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(124), 1,
      anon_sym_COLON_COLON,
    ACTIONS(126), 1,
      anon_sym_COLON,
    STATE(24), 1,
      sym_comment,
  [436] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [447] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(128), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_comment,
  [457] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_COLON_COLON,
    STATE(27), 1,
      sym_comment,
  [467] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(28), 1,
      sym_comment,
  [477] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      sym_comment,
  [487] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_comment,
  [497] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(138), 1,
      sym_identifier,
    STATE(31), 1,
      sym_comment,
  [507] = 3,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      aux_sym_comment_token1,
    STATE(32), 1,
      sym_comment,
  [517] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(142), 1,
      anon_sym_COLON_COLON,
    STATE(33), 1,
      sym_comment,
  [527] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(144), 1,
      sym_path,
    STATE(34), 1,
      sym_comment,
  [537] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(146), 1,
      sym_path,
    STATE(35), 1,
      sym_comment,
  [547] = 1,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 43,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 148,
  [SMALL_STATE(9)] = 166,
  [SMALL_STATE(10)] = 184,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 220,
  [SMALL_STATE(13)] = 238,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 274,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 310,
  [SMALL_STATE(18)] = 328,
  [SMALL_STATE(19)] = 346,
  [SMALL_STATE(20)] = 364,
  [SMALL_STATE(21)] = 380,
  [SMALL_STATE(22)] = 396,
  [SMALL_STATE(23)] = 410,
  [SMALL_STATE(24)] = 423,
  [SMALL_STATE(25)] = 436,
  [SMALL_STATE(26)] = 447,
  [SMALL_STATE(27)] = 457,
  [SMALL_STATE(28)] = 467,
  [SMALL_STATE(29)] = 477,
  [SMALL_STATE(30)] = 487,
  [SMALL_STATE(31)] = 497,
  [SMALL_STATE(32)] = 507,
  [SMALL_STATE(33)] = 517,
  [SMALL_STATE(34)] = 527,
  [SMALL_STATE(35)] = 537,
  [SMALL_STATE(36)] = 547,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 2, 0, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_return, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_return, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_value, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_value, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_entry, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_entry, 2, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_statement, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verify_statement, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 6, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 7, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 7, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [136] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lmy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lmy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
