/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_aka = 4,
  anon_sym_COLON_COLON = 5,
  anon_sym_verify = 6,
  anon_sym_import = 7,
  anon_sym_LBRACE = 8,
  anon_sym_COMMA = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_DASH_DASH = 12,
  anon_sym_SLASH_SLASH = 13,
  aux_sym_comment_token1 = 14,
  anon_sym_LT_LT = 15,
  anon_sym_PIPE_PIPE = 16,
  anon_sym_GT_GT = 17,
  aux_sym_text_line_token1 = 18,
  sym_string = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  sym_version = 22,
  sym_number = 23,
  sym_path_value = 24,
  sym_path = 25,
  sym_identifier = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym_section = 29,
  sym_scope_entry = 30,
  sym_scope_return = 31,
  sym_verify_statement = 32,
  sym_import_statement = 33,
  sym_assignment = 34,
  sym_list_item = 35,
  sym_comment = 36,
  sym_multiline_open = 37,
  sym_multiline_close = 38,
  sym_text_line = 39,
  sym__value = 40,
  sym_raw_value = 41,
  sym_boolean = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_import_statement_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_aka] = "aka",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_verify] = "verify",
  [anon_sym_import] = "import",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_GT_GT] = ">>",
  [aux_sym_text_line_token1] = "text_line_token1",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_version] = "version",
  [sym_number] = "number",
  [sym_path_value] = "path_value",
  [sym_path] = "path",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_section] = "section",
  [sym_scope_entry] = "scope_entry",
  [sym_scope_return] = "scope_return",
  [sym_verify_statement] = "verify_statement",
  [sym_import_statement] = "import_statement",
  [sym_assignment] = "assignment",
  [sym_list_item] = "list_item",
  [sym_comment] = "comment",
  [sym_multiline_open] = "multiline_open",
  [sym_multiline_close] = "multiline_close",
  [sym_text_line] = "text_line",
  [sym__value] = "_value",
  [sym_raw_value] = "raw_value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_statement_repeat1] = "import_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_aka] = anon_sym_aka,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_verify] = anon_sym_verify,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [aux_sym_text_line_token1] = aux_sym_text_line_token1,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_version] = sym_version,
  [sym_number] = sym_number,
  [sym_path_value] = sym_path_value,
  [sym_path] = sym_path,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_section] = sym_section,
  [sym_scope_entry] = sym_scope_entry,
  [sym_scope_return] = sym_scope_return,
  [sym_verify_statement] = sym_verify_statement,
  [sym_import_statement] = sym_import_statement,
  [sym_assignment] = sym_assignment,
  [sym_list_item] = sym_list_item,
  [sym_comment] = sym_comment,
  [sym_multiline_open] = sym_multiline_open,
  [sym_multiline_close] = sym_multiline_close,
  [sym_text_line] = sym_text_line,
  [sym__value] = sym__value,
  [sym_raw_value] = sym_raw_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_statement_repeat1] = aux_sym_import_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_aka] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_verify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_text_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_path_value] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_return] = {
    .visible = true,
    .named = true,
  },
  [sym_verify_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_open] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_close] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '"', 2,
        ',', 34,
        '-', 4,
        '/', 6,
        ':', 36,
        '<', 9,
        '>', 10,
        '[', 20,
        ']', 22,
        'a', 113,
        'f', 106,
        'i', 115,
        't', 118,
        'v', 110,
        '{', 33,
        '|', 11,
        '}', 35,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(99);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 51,
        '/', 58,
        '<', 92,
        'f', 61,
        't', 81,
        '|', 94,
        '\t', 53,
        ' ', 53,
        0x17f, 91,
        0x212a, 91,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '@') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '}') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      END_STATE();
    case 9:
      if (lookahead == '<') ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == '|') ADVANCE(47);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 13:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 14:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '"', 51,
        '-', 56,
        '/', 58,
        ':', 60,
        '<', 92,
        '>', 93,
        '[', 21,
        'f', 61,
        'i', 74,
        't', 81,
        'v', 66,
        '|', 94,
        '\t', 52,
        ' ', 52,
        0x17f, 91,
        0x212a, 91,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '-', 56,
        '/', 59,
        ':', 60,
        '>', 93,
        '[', 21,
        'a', 71,
        'i', 73,
        'v', 63,
        '|', 94,
        '\t', 54,
        ' ', 54,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '-', 56,
        '/', 59,
        ':', 60,
        '>', 93,
        '[', 21,
        'i', 73,
        'v', 63,
        '|', 94,
        '\t', 55,
        ' ', 55,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_aka);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_aka);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '"') ADVANCE(98);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      ADVANCE_MAP(
        '"', 51,
        '-', 56,
        '/', 58,
        ':', 60,
        '<', 92,
        '>', 93,
        '[', 21,
        'f', 61,
        'i', 74,
        't', 81,
        'v', 66,
        '|', 94,
        '\t', 52,
        ' ', 52,
        0x17f, 91,
        0x212a, 91,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      ADVANCE_MAP(
        '"', 51,
        '/', 58,
        '<', 92,
        'f', 61,
        't', 81,
        '|', 94,
        '\t', 53,
        ' ', 53,
        0x17f, 91,
        0x212a, 91,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      ADVANCE_MAP(
        '-', 56,
        '/', 59,
        ':', 60,
        '>', 93,
        '[', 21,
        'a', 71,
        'i', 73,
        'v', 63,
        '|', 94,
        '\t', 54,
        ' ', 54,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      ADVANCE_MAP(
        '-', 56,
        '/', 59,
        ':', 60,
        '>', 93,
        '[', 21,
        'i', 73,
        'v', 63,
        '|', 94,
        '\t', 55,
        ' ', 55,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '.') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '/') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'a') ADVANCE(72);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'e') ADVANCE(101);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'e') ADVANCE(103);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'e') ADVANCE(82);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'f') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'f') ADVANCE(89);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'i') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'k') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'l') ADVANCE(84);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'm') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'm') ADVANCE(78);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'o') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'o') ADVANCE(83);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'p') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'p') ADVANCE(76);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'r') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'r') ADVANCE(87);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'r') ADVANCE(70);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'r') ADVANCE(86);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 's') ADVANCE(65);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'u') ADVANCE(64);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'y') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == 'y') ADVANCE(28);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '<') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead == '|') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_text_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(97);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(91);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_version);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(114);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(100);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(102);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(119);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(124);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'i') ADVANCE(111);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'k') ADVANCE(107);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(121);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'm') ADVANCE(117);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(120);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'p') ADVANCE(116);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(123);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(112);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(122);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 's') ADVANCE(109);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(108);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == 'y') ADVANCE(27);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(126);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_path_value);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(128);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 42},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 0},
  [43] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_aka] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_verify] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_path_value] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym__definition] = STATE(12),
    [sym_section] = STATE(11),
    [sym_scope_entry] = STATE(11),
    [sym_scope_return] = STATE(11),
    [sym_verify_statement] = STATE(11),
    [sym_import_statement] = STATE(11),
    [sym_assignment] = STATE(11),
    [sym_list_item] = STATE(11),
    [sym_comment] = STATE(1),
    [sym_multiline_close] = STATE(11),
    [sym_text_line] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_COLON_COLON] = ACTIONS(11),
    [anon_sym_verify] = ACTIONS(13),
    [anon_sym_import] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(17),
    [anon_sym_SLASH_SLASH] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(21),
    [anon_sym_GT_GT] = ACTIONS(21),
    [aux_sym_text_line_token1] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(12),
    [sym_section] = STATE(11),
    [sym_scope_entry] = STATE(11),
    [sym_scope_return] = STATE(11),
    [sym_verify_statement] = STATE(11),
    [sym_import_statement] = STATE(11),
    [sym_assignment] = STATE(11),
    [sym_list_item] = STATE(11),
    [sym_comment] = STATE(2),
    [sym_multiline_close] = STATE(11),
    [sym_text_line] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_COLON_COLON] = ACTIONS(11),
    [anon_sym_verify] = ACTIONS(13),
    [anon_sym_import] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(17),
    [anon_sym_SLASH_SLASH] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(21),
    [anon_sym_GT_GT] = ACTIONS(21),
    [aux_sym_text_line_token1] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym_comment] = STATE(3),
    [sym_multiline_open] = STATE(13),
    [sym__value] = STATE(19),
    [sym_raw_value] = STATE(13),
    [sym_boolean] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(29),
    [aux_sym_source_file_token1] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_COLON_COLON] = ACTIONS(31),
    [anon_sym_verify] = ACTIONS(31),
    [anon_sym_import] = ACTIONS(31),
    [anon_sym_DASH_DASH] = ACTIONS(31),
    [anon_sym_SLASH_SLASH] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(33),
    [anon_sym_PIPE_PIPE] = ACTIONS(33),
    [anon_sym_GT_GT] = ACTIONS(31),
    [aux_sym_text_line_token1] = ACTIONS(35),
    [sym_string] = ACTIONS(37),
    [anon_sym_true] = ACTIONS(39),
    [anon_sym_false] = ACTIONS(39),
    [sym_version] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
    [sym_path_value] = ACTIONS(37),
    [sym_identifier] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym__definition] = STATE(12),
    [sym_section] = STATE(11),
    [sym_scope_entry] = STATE(11),
    [sym_scope_return] = STATE(11),
    [sym_verify_statement] = STATE(11),
    [sym_import_statement] = STATE(11),
    [sym_assignment] = STATE(11),
    [sym_list_item] = STATE(11),
    [sym_comment] = STATE(4),
    [sym_multiline_close] = STATE(11),
    [sym_text_line] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(41),
    [aux_sym_source_file_token1] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(46),
    [anon_sym_COLON_COLON] = ACTIONS(49),
    [anon_sym_verify] = ACTIONS(52),
    [anon_sym_import] = ACTIONS(55),
    [anon_sym_DASH_DASH] = ACTIONS(58),
    [anon_sym_SLASH_SLASH] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(61),
    [anon_sym_GT_GT] = ACTIONS(61),
    [aux_sym_text_line_token1] = ACTIONS(64),
    [sym_identifier] = ACTIONS(67),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(35), 1,
      aux_sym_text_line_token1,
    STATE(5), 1,
      sym_comment,
    STATE(14), 1,
      sym__value,
    ACTIONS(33), 2,
      anon_sym_LT_LT,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 3,
      sym_multiline_open,
      sym_raw_value,
      sym_boolean,
    ACTIONS(37), 5,
      sym_string,
      sym_version,
      sym_number,
      sym_path_value,
      sym_identifier,
  [33] = 5,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      anon_sym_aka,
    STATE(6), 1,
      sym_comment,
    ACTIONS(72), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [58] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_comment,
    ACTIONS(78), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [80] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_comment,
    ACTIONS(82), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [102] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_comment,
    ACTIONS(86), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [124] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_comment,
    ACTIONS(90), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [146] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_comment,
    ACTIONS(94), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [168] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      sym_comment,
    ACTIONS(98), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [190] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_comment,
    ACTIONS(102), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [212] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_comment,
    ACTIONS(106), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [234] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_comment,
    ACTIONS(110), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [256] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_comment,
    ACTIONS(114), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [278] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_comment,
    ACTIONS(118), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [300] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      sym_comment,
    ACTIONS(122), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [322] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_comment,
    ACTIONS(126), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [344] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_comment,
    ACTIONS(130), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [366] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      sym_comment,
    ACTIONS(134), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [388] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_comment,
    ACTIONS(138), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [410] = 4,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_comment,
    ACTIONS(142), 10,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_verify,
      anon_sym_import,
      anon_sym_DASH_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_GT_GT,
      aux_sym_text_line_token1,
      sym_identifier,
  [432] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_import_statement_repeat1,
  [448] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_import_statement_repeat1,
  [464] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_comment,
      aux_sym_import_statement_repeat1,
  [478] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(155), 1,
      anon_sym_COLON_COLON,
    ACTIONS(157), 1,
      anon_sym_COLON,
    STATE(27), 1,
      sym_comment,
  [491] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      sym_identifier,
    STATE(28), 1,
      sym_comment,
  [504] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [515] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      sym_comment,
  [525] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(165), 1,
      anon_sym_LBRACK,
    STATE(31), 1,
      sym_comment,
  [535] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_comment,
  [545] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(33), 1,
      sym_comment,
  [555] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(171), 1,
      sym_path,
    STATE(34), 1,
      sym_comment,
  [565] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(173), 1,
      anon_sym_COLON_COLON,
    STATE(35), 1,
      sym_comment,
  [575] = 3,
    ACTIONS(19), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(175), 1,
      aux_sym_comment_token1,
    STATE(36), 1,
      sym_comment,
  [585] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(37), 1,
      sym_comment,
  [595] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    STATE(38), 1,
      sym_comment,
  [605] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_COLON_COLON,
    STATE(39), 1,
      sym_comment,
  [615] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(183), 1,
      sym_path,
    STATE(40), 1,
      sym_comment,
  [625] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(41), 1,
      sym_comment,
  [635] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(187), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_comment,
  [645] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 33,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 80,
  [SMALL_STATE(9)] = 102,
  [SMALL_STATE(10)] = 124,
  [SMALL_STATE(11)] = 146,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 190,
  [SMALL_STATE(14)] = 212,
  [SMALL_STATE(15)] = 234,
  [SMALL_STATE(16)] = 256,
  [SMALL_STATE(17)] = 278,
  [SMALL_STATE(18)] = 300,
  [SMALL_STATE(19)] = 322,
  [SMALL_STATE(20)] = 344,
  [SMALL_STATE(21)] = 366,
  [SMALL_STATE(22)] = 388,
  [SMALL_STATE(23)] = 410,
  [SMALL_STATE(24)] = 432,
  [SMALL_STATE(25)] = 448,
  [SMALL_STATE(26)] = 464,
  [SMALL_STATE(27)] = 478,
  [SMALL_STATE(28)] = 491,
  [SMALL_STATE(29)] = 504,
  [SMALL_STATE(30)] = 515,
  [SMALL_STATE(31)] = 525,
  [SMALL_STATE(32)] = 535,
  [SMALL_STATE(33)] = 545,
  [SMALL_STATE(34)] = 555,
  [SMALL_STATE(35)] = 565,
  [SMALL_STATE(36)] = 575,
  [SMALL_STATE(37)] = 585,
  [SMALL_STATE(38)] = 595,
  [SMALL_STATE(39)] = 605,
  [SMALL_STATE(40)] = 615,
  [SMALL_STATE(41)] = 625,
  [SMALL_STATE(42)] = 635,
  [SMALL_STATE(43)] = 645,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 2, 0, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_value, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_value, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_close, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_close, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_line, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_open, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_open, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_entry, 2, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_entry, 2, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_return, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_return, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_statement, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verify_statement, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 3),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 6, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 7, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 7, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 7, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 7, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [179] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lmy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lmy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
