/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_aka = 4,
  anon_sym_COLON_COLON = 5,
  anon_sym_verify = 6,
  anon_sym_import = 7,
  anon_sym_LBRACE = 8,
  anon_sym_COMMA = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_DASH_DASH = 12,
  anon_sym_SLASH_SLASH = 13,
  aux_sym_comment_token1 = 14,
  anon_sym_LT_LT = 15,
  aux_sym_multiline_fold_token1 = 16,
  anon_sym_GT_GT = 17,
  anon_sym_PIPE_PIPE = 18,
  sym_string = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  sym_version = 22,
  sym_number = 23,
  sym_path_value = 24,
  sym_path = 25,
  sym_identifier = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym_section = 29,
  sym_scope_entry = 30,
  sym_scope_return = 31,
  sym_verify_statement = 32,
  sym_import_statement = 33,
  sym_assignment = 34,
  sym_list_item = 35,
  sym_comment = 36,
  sym_multiline_fold = 37,
  sym_multiline_preserve = 38,
  sym__value = 39,
  sym_raw_value = 40,
  sym_boolean = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_import_statement_repeat1 = 43,
  aux_sym_multiline_fold_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_aka] = "aka",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_verify] = "verify",
  [anon_sym_import] = "import",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LT_LT] = "<<",
  [aux_sym_multiline_fold_token1] = "multiline_fold_token1",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_PIPE_PIPE] = "||",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_version] = "version",
  [sym_number] = "number",
  [sym_path_value] = "path_value",
  [sym_path] = "path",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_section] = "section",
  [sym_scope_entry] = "scope_entry",
  [sym_scope_return] = "scope_return",
  [sym_verify_statement] = "verify_statement",
  [sym_import_statement] = "import_statement",
  [sym_assignment] = "assignment",
  [sym_list_item] = "list_item",
  [sym_comment] = "comment",
  [sym_multiline_fold] = "multiline_fold",
  [sym_multiline_preserve] = "multiline_preserve",
  [sym__value] = "_value",
  [sym_raw_value] = "raw_value",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_import_statement_repeat1] = "import_statement_repeat1",
  [aux_sym_multiline_fold_repeat1] = "multiline_fold_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_aka] = anon_sym_aka,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_verify] = anon_sym_verify,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [aux_sym_multiline_fold_token1] = aux_sym_multiline_fold_token1,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_version] = sym_version,
  [sym_number] = sym_number,
  [sym_path_value] = sym_path_value,
  [sym_path] = sym_path,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_section] = sym_section,
  [sym_scope_entry] = sym_scope_entry,
  [sym_scope_return] = sym_scope_return,
  [sym_verify_statement] = sym_verify_statement,
  [sym_import_statement] = sym_import_statement,
  [sym_assignment] = sym_assignment,
  [sym_list_item] = sym_list_item,
  [sym_comment] = sym_comment,
  [sym_multiline_fold] = sym_multiline_fold,
  [sym_multiline_preserve] = sym_multiline_preserve,
  [sym__value] = sym__value,
  [sym_raw_value] = sym_raw_value,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_import_statement_repeat1] = aux_sym_import_statement_repeat1,
  [aux_sym_multiline_fold_repeat1] = aux_sym_multiline_fold_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_aka] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_verify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_multiline_fold_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_path_value] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_return] = {
    .visible = true,
    .named = true,
  },
  [sym_verify_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_fold] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_preserve] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_fold_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
  [2] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        '"', 2,
        ',', 37,
        '-', 4,
        '/', 6,
        ':', 39,
        '<', 12,
        '>', 13,
        '[', 23,
        ']', 25,
        'a', 104,
        'f', 97,
        'i', 106,
        't', 109,
        'v', 101,
        '{', 36,
        '|', 14,
        '}', 38,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(89);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '/') ADVANCE(2);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(118);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '}') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == '<') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(85);
      END_STATE();
    case 14:
      if (lookahead == '|') ADVANCE(87);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 16:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(118);
      END_STATE();
    case 17:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(79);
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        '-', 4,
        '/', 5,
        ':', 11,
        '[', 23,
        'a', 123,
        'i', 124,
        'v', 120,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        '-', 4,
        '/', 5,
        ':', 11,
        '[', 23,
        'i', 124,
        'v', 120,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_aka);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_aka);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_verify);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(28);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      ADVANCE_MAP(
        '"', 51,
        '-', 52,
        '/', 7,
        ':', 72,
        '<', 74,
        '[', 24,
        'f', 53,
        'i', 60,
        't', 63,
        'v', 56,
        '|', 76,
        '\t', 49,
        ' ', 49,
        0x17f, 73,
        0x212a, 73,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      ADVANCE_MAP(
        '"', 51,
        '/', 7,
        '<', 74,
        'f', 53,
        't', 63,
        '|', 76,
        '\t', 50,
        ' ', 50,
        0x17f, 73,
        0x212a, 73,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'f') ADVANCE(69);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'm') ADVANCE(62);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'o') ADVANCE(65);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'r') ADVANCE(68);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 's') ADVANCE(55);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'u') ADVANCE(54);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == 'y') ADVANCE(30);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '.') ADVANCE(77);
      if (lookahead == '/') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '>') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '|') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(96);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '>') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '|') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_multiline_fold_token1);
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 51,
        '-', 52,
        '/', 7,
        ':', 72,
        '<', 74,
        '[', 24,
        'f', 53,
        'i', 60,
        't', 63,
        'v', 56,
        '|', 76,
        '\t', 49,
        ' ', 49,
        0x17f, 73,
        0x212a, 73,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(73);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_version);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == '/') ADVANCE(117);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(79);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(105);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(91);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(93);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(110);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'f') ADVANCE(115);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'i') ADVANCE(102);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'k') ADVANCE(98);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(112);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'm') ADVANCE(108);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(111);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'p') ADVANCE(107);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(114);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(103);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(113);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 's') ADVANCE(100);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(99);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'y') ADVANCE(31);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_path_value);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(117);
      if (lookahead == '@' ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_path_value);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'f') ADVANCE(130);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'i') ADVANCE(121);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'k') ADVANCE(119);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'm') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(128);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'p') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(122);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(129);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'y') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(131);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 84},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 50},
  [6] = {.lex_state = 19},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 20},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 20},
  [13] = {.lex_state = 20},
  [14] = {.lex_state = 20},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 81},
  [26] = {.lex_state = 82},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 82},
  [30] = {.lex_state = 81},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 83},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 44},
  [54] = {.lex_state = 0},
  [55] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_aka] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_verify] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_path_value] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym__definition] = STATE(24),
    [sym_section] = STATE(13),
    [sym_scope_entry] = STATE(13),
    [sym_scope_return] = STATE(13),
    [sym_verify_statement] = STATE(13),
    [sym_import_statement] = STATE(13),
    [sym_assignment] = STATE(13),
    [sym_list_item] = STATE(13),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_COLON_COLON] = ACTIONS(11),
    [anon_sym_verify] = ACTIONS(13),
    [anon_sym_import] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(17),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_identifier] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym_comment] = STATE(2),
    [sym_multiline_fold] = STATE(9),
    [sym_multiline_preserve] = STATE(9),
    [sym__value] = STATE(16),
    [sym_raw_value] = STATE(9),
    [sym_boolean] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym_source_file_token1] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_COLON_COLON] = ACTIONS(23),
    [anon_sym_verify] = ACTIONS(23),
    [anon_sym_import] = ACTIONS(23),
    [anon_sym_DASH_DASH] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_LT_LT] = ACTIONS(27),
    [aux_sym_multiline_fold_token1] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [sym_string] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_version] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_path_value] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      aux_sym_source_file_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      anon_sym_verify,
    ACTIONS(15), 1,
      anon_sym_import,
    ACTIONS(17), 1,
      anon_sym_DASH_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 1,
      sym__definition,
    STATE(13), 7,
      sym_section,
      sym_scope_entry,
      sym_scope_return,
      sym_verify_statement,
      sym_import_statement,
      sym_assignment,
      sym_list_item,
  [46] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym_source_file_token1,
    ACTIONS(44), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_COLON_COLON,
    ACTIONS(50), 1,
      anon_sym_verify,
    ACTIONS(53), 1,
      anon_sym_import,
    ACTIONS(56), 1,
      anon_sym_DASH_DASH,
    ACTIONS(59), 1,
      sym_identifier,
    STATE(24), 1,
      sym__definition,
    STATE(4), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(13), 7,
      sym_section,
      sym_scope_entry,
      sym_scope_return,
      sym_verify_statement,
      sym_import_statement,
      sym_assignment,
      sym_list_item,
  [90] = 9,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(27), 1,
      anon_sym_LT_LT,
    ACTIONS(29), 1,
      aux_sym_multiline_fold_token1,
    ACTIONS(31), 1,
      anon_sym_PIPE_PIPE,
    STATE(5), 1,
      sym_comment,
    STATE(11), 1,
      sym__value,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 4,
      sym_multiline_fold,
      sym_multiline_preserve,
      sym_raw_value,
      sym_boolean,
    ACTIONS(33), 5,
      sym_string,
      sym_version,
      sym_number,
      sym_path_value,
      sym_identifier,
  [126] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      anon_sym_aka,
    STATE(6), 1,
      sym_comment,
    ACTIONS(66), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(62), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [148] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(7), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [167] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(8), 1,
      sym_comment,
    ACTIONS(74), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [186] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(9), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [205] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(10), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [224] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(11), 1,
      sym_comment,
    ACTIONS(86), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [243] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(90), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [262] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(94), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [281] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(98), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [300] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(102), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(100), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [319] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(106), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [338] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(110), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [357] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(114), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [376] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(118), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [395] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(122), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [414] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(126), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [433] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [452] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [471] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_verify,
      anon_sym_import,
      sym_identifier,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_LBRACK,
      anon_sym_COLON_COLON,
      anon_sym_DASH_DASH,
  [490] = 5,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      aux_sym_source_file_token1,
    ACTIONS(142), 1,
      aux_sym_multiline_fold_token1,
    ACTIONS(144), 1,
      anon_sym_GT_GT,
    STATE(25), 1,
      sym_comment,
  [506] = 5,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      aux_sym_source_file_token1,
    ACTIONS(142), 1,
      aux_sym_multiline_fold_token1,
    ACTIONS(146), 1,
      anon_sym_PIPE_PIPE,
    STATE(26), 1,
      sym_comment,
  [522] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_import_statement_repeat1,
  [538] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_comment,
    STATE(31), 1,
      aux_sym_import_statement_repeat1,
  [554] = 5,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      aux_sym_source_file_token1,
    ACTIONS(142), 1,
      aux_sym_multiline_fold_token1,
    ACTIONS(154), 1,
      anon_sym_PIPE_PIPE,
    STATE(29), 1,
      sym_comment,
  [570] = 5,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      aux_sym_source_file_token1,
    ACTIONS(142), 1,
      aux_sym_multiline_fold_token1,
    ACTIONS(156), 1,
      anon_sym_GT_GT,
    STATE(30), 1,
      sym_comment,
  [586] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym_comment,
      aux_sym_import_statement_repeat1,
  [600] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(163), 1,
      aux_sym_source_file_token1,
    STATE(32), 2,
      sym_comment,
      aux_sym_multiline_fold_repeat1,
  [611] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(166), 1,
      aux_sym_source_file_token1,
    STATE(32), 1,
      aux_sym_multiline_fold_repeat1,
    STATE(33), 1,
      sym_comment,
  [624] = 4,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(140), 1,
      aux_sym_source_file_token1,
    ACTIONS(168), 1,
      aux_sym_multiline_fold_token1,
    STATE(34), 1,
      sym_comment,
  [637] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(170), 1,
      aux_sym_source_file_token1,
    STATE(32), 1,
      aux_sym_multiline_fold_repeat1,
    STATE(35), 1,
      sym_comment,
  [650] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(172), 1,
      aux_sym_source_file_token1,
    STATE(35), 1,
      aux_sym_multiline_fold_repeat1,
    STATE(36), 1,
      sym_comment,
  [663] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(37), 1,
      sym_comment,
  [676] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(178), 1,
      anon_sym_COLON_COLON,
    ACTIONS(180), 1,
      anon_sym_COLON,
    STATE(38), 1,
      sym_comment,
  [689] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(182), 1,
      aux_sym_source_file_token1,
    STATE(33), 1,
      aux_sym_multiline_fold_repeat1,
    STATE(39), 1,
      sym_comment,
  [702] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(40), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [713] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(184), 1,
      sym_identifier,
    STATE(41), 1,
      sym_comment,
  [723] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(186), 1,
      sym_identifier,
    STATE(42), 1,
      sym_comment,
  [733] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(188), 1,
      anon_sym_COLON_COLON,
    STATE(43), 1,
      sym_comment,
  [743] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(190), 1,
      sym_path,
    STATE(44), 1,
      sym_comment,
  [753] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(192), 1,
      sym_path,
    STATE(45), 1,
      sym_comment,
  [763] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_comment,
  [773] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(196), 1,
      anon_sym_LBRACK,
    STATE(47), 1,
      sym_comment,
  [783] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      sym_comment,
  [793] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(200), 1,
      anon_sym_COLON_COLON,
    STATE(49), 1,
      sym_comment,
  [803] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(202), 1,
      aux_sym_source_file_token1,
    STATE(50), 1,
      sym_comment,
  [813] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(51), 1,
      sym_comment,
  [823] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_comment,
  [833] = 3,
    ACTIONS(25), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(208), 1,
      aux_sym_comment_token1,
    STATE(53), 1,
      sym_comment,
  [843] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
    STATE(54), 1,
      sym_comment,
  [853] = 1,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 148,
  [SMALL_STATE(8)] = 167,
  [SMALL_STATE(9)] = 186,
  [SMALL_STATE(10)] = 205,
  [SMALL_STATE(11)] = 224,
  [SMALL_STATE(12)] = 243,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 281,
  [SMALL_STATE(15)] = 300,
  [SMALL_STATE(16)] = 319,
  [SMALL_STATE(17)] = 338,
  [SMALL_STATE(18)] = 357,
  [SMALL_STATE(19)] = 376,
  [SMALL_STATE(20)] = 395,
  [SMALL_STATE(21)] = 414,
  [SMALL_STATE(22)] = 433,
  [SMALL_STATE(23)] = 452,
  [SMALL_STATE(24)] = 471,
  [SMALL_STATE(25)] = 490,
  [SMALL_STATE(26)] = 506,
  [SMALL_STATE(27)] = 522,
  [SMALL_STATE(28)] = 538,
  [SMALL_STATE(29)] = 554,
  [SMALL_STATE(30)] = 570,
  [SMALL_STATE(31)] = 586,
  [SMALL_STATE(32)] = 600,
  [SMALL_STATE(33)] = 611,
  [SMALL_STATE(34)] = 624,
  [SMALL_STATE(35)] = 637,
  [SMALL_STATE(36)] = 650,
  [SMALL_STATE(37)] = 663,
  [SMALL_STATE(38)] = 676,
  [SMALL_STATE(39)] = 689,
  [SMALL_STATE(40)] = 702,
  [SMALL_STATE(41)] = 713,
  [SMALL_STATE(42)] = 723,
  [SMALL_STATE(43)] = 733,
  [SMALL_STATE(44)] = 743,
  [SMALL_STATE(45)] = 753,
  [SMALL_STATE(46)] = 763,
  [SMALL_STATE(47)] = 773,
  [SMALL_STATE(48)] = 783,
  [SMALL_STATE(49)] = 793,
  [SMALL_STATE(50)] = 803,
  [SMALL_STATE(51)] = 813,
  [SMALL_STATE(52)] = 823,
  [SMALL_STATE(53)] = 833,
  [SMALL_STATE(54)] = 843,
  [SMALL_STATE(55)] = 853,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 2, 0, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 6, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 7, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 7, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_entry, 2, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_entry, 2, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_return, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope_return, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_statement, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verify_statement, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_fold, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_fold, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_preserve, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_preserve, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_fold, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_fold, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_preserve, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_preserve, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_value, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_value, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 7, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 7, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multiline_fold_repeat1, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_statement_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_fold_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_fold_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [210] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lmy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lmy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
